### ISSUE TITLE
On Windows 10, export freezes if a speech interrupts another speech

### ISSUE THREAD

**Issue by FrancBanc** [lightsoutgames/godot-tts#2]
I am using Windows 10 64 bit, Desktop

If interrupt is true, the exported app will freeze when it tries to interrupt. Godot itself does not freeze though.
However if interrupt is false, it does not freeze; the new speech just plays after the current one is finished.

I have included a simple project file that has 3 nodes: A button that turns TTS interrupt on and off, a LineEdit to input text, and a Button that triggers TTS to speak.

[Godot-TTS.zip](https://github.com/lightsoutgames/godot-tts/files/4867188/Godot-TTS.zip)

**Comment by ndarilek** [comment]
Give V0.5.4 a shot. I tweaked the underlying TTS logic to recreate the 
player whenever speech is interrupted. Now I can spam your test project 
with lots of TTS and it seems to handle interruption without freezing.


Please let me know if that works for you--WinRT is the platform I have 
the hardest time testing on. Thanks for the report!

**Comment by FrancBanc** [comment]
Yes it works great on Windows now, thank you!
Oh onto another thing though. I notice that windows doesn't send a "done" signal. If you know anyway to implement it I could try, since I use windows. However I'm not sure what coding API you're using with windows to make the DLL. I'm not even sure how to make DLL's but I could try to learn haha.

**Comment by ndarilek** [comment]
Sounds like another issue, but you may be able to get this working 
yourself and submit a PR. The "done" signal is sent in TTS.gd--I just 
poll the synth to see if it is speaking in _process, with a bit of 
logic. You can actually see my ugly `print` statements there where I 
tried to get this working on Android--forgot I left those in. :) I also 
just ensured that the TTS node always runs even if the game is paused, 
so you may want to grab it from master and replace it in your downloaded 
addon to see if that fixes things.


If you can get that working and submit a PR, that'd be helpful. 
Otherwise, if you can identify the logic error in `_process`, that'd 
help too. Maybe `is_speaking` is broken subtly?


Thanks.

**Comment by ndarilek** [comment]
Actually, I'm pretty sure I figured out your other issue. Forgot to 
indicate in the underlying TTS library that WinRT can now detect when 
speaking, which is needed for the signal to send.


I'll have a new version up in the next couple hours that should fix 
this. Watch the releases page.

**Comment by FrancBanc** [comment]
Yes, I downloaded the newest version and it works perfectly! Thank you so much!

**Comment by ndarilek** [comment]
You're welcome. Mind if I ask what you're doing with this? Nice to see 
more folks using my work, and I'm always curious what for.
